# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tf-eu-west-2-hmpps-delius-stage-remote-state"
    dynamodb_table = "tf-eu-west-2-hmpps-delius-stage-lock-table"
    encrypt        = true
    key            = "iaps/common/terraform.tfstate"
    region         = "eu-west-2"
  }
}
